# Based on https://github.com/raywenderlich/swift-style-guide

excluded:
  - ${PWD}/Derived
  - ${PWD}/Tuist/Dependencies

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - file_types_order
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

file_types_order:
  order:
    - SwiftLintFramework.FileType.supportingType
    - SwiftLintFramework.FileType.mainType
    - SwiftLintFramework.FileType.extension
    - SwiftLintFramework.FileType.previewProvider
    - SwiftLintFramework.FileType.libraryContentProvider

force_cast: warning

force_try: warning

function_body_length:
  warning: 60

identifier_name:
  min_length: 2

indentation_width:
  indentation_width: 2

legacy_hashing: error

line_length:
  error: 80
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

type_contents_order:
  order:
    - SwiftLintFramework.TypeContent.case
    - SwiftLintFramework.TypeContent.typeAlias
    - SwiftLintFramework.TypeContent.associatedType
    - SwiftLintFramework.TypeContent.subtype
    - SwiftLintFramework.TypeContent.typeProperty
    - SwiftLintFramework.TypeContent.instanceProperty
    - SwiftLintFramework.TypeContent.ibInspectable
    - SwiftLintFramework.TypeContent.ibOutlet
    - SwiftLintFramework.TypeContent.initializer
    - SwiftLintFramework.TypeContent.typeMethod
    - SwiftLintFramework.TypeContent.viewLifeCycleMethod
    - SwiftLintFramework.TypeContent.ibAction
    - SwiftLintFramework.TypeContent.otherMethod
    - SwiftLintFramework.TypeContent.subscript
    - SwiftLintFramework.TypeContent.deinitializer

vertical_whitespace:
  max_empty_lines: 1

switch_case_alignment:
  indented_cases: true
